version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: teus_app_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=teus_app
    restart: unless-stopped
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: teus_app_server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: teus_app_frontend
    ports:
      - "5173:5173"

    depends_on:
      - server
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mongodb_data: 